##set up R env
install.packages("rmarkdown",repos = "http://cran.us.r-project.org")
install.packages("remotes",repos = "http://cran.us.r-project.org")
install.packages("gridExtra",repos = "http://cran.us.r-project.org")
install.packages("BiocManager",repos = "http://cran.us.r-project.org")
install.packages("ggfortify",repos = "http://cran.us.r-project.org")
install.packages("ggrepel",repos = "http://cran.us.r-project.org")
install.packages("umap",repos = "http://cran.us.r-project.org")

library(BiocManager)
BiocManager::install("EnsDb.Hsapiens.v86")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("DESeq2")
BiocManager::install("tximport")
BiocManager::install("tximportData")
BiocManager::install("apeglm")

library(remotes)
remotes::install_github("rstudio/reticulate")
remotes::install_github("sgosline/mpnstXenoModeling")
remotes::install_github("biodataganache/leapR")
