---
title: "DE analysis"
author: "Jess Bade"
date: "8/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(remotes)
if(!require(mpnstXenoModeling)){
  remotes::install_github('sgosline/mpnstXenoModeling')
  library(mpnstXenoModeling)
}

if(!require('dplyr')){
  install.pacakges('dplyr')
  library(dplyr)
}
if(!require('tidyr')){
  install.pacakges('tidyr')
  library(tidyr)
}
if(!require('EnsDb.Hsapiens.v86')){
  BiocManager::install('EnsDb.Hsapiens.v86')
  library(EnsDb.Hsapiens.v86)
}

```

## Load data from synapse query


```{r loadData,warning=FALSE}
#These three commands load RNAseq data
syn<-reticulate::import('synapseclient')$login()
data.tab<-syn$tableQuery('select * from syn24215021')$asDataFrame()
rnaSeq<<-mpnstXenoModeling::dataFromSynTable(data.tab,syn,'RNASeq')#%>%


master.table<-rnaSeq

##select clinical variables
var.ID<-rnaSeq%>%
  dplyr::select(Sample,synid,Age,Sex,MicroTissueQuality,Location,Size,Clinical.Status)%>%distinct()%>%
  tibble::column_to_rownames('synid')


##select gene mapping
identifiers<-rnaSeq%>%
  dplyr::select(TXID,Symbol)%>%distinct()
```

## Format the clinical data to distinct factors


```{r formatting, warning=FALSE}

format_clinical_data <- function(df) {
  #Modify table naming for data subsetting
  names(df)[names(df) == "Clinical Status"] <- "Clinical.Status"
  df$Clinical.Status = gsub("NED","Alive",df$Clinical.Status)
  df$Clinical.Status = gsub("Alive with metastatic disease","Alive",df$Clinical.Status)
  df$Clinical.Status = gsub("Unknown",NA,df$Clinical.Status)
  df$UpdatedTissueQuality <- df$MicroTissueQuality
  df$UpdatedTissueQuality <- gsub("Good", "Robust",df$UpdatedTissueQuality)
  df$Age <- ifelse(df$Age < 19,  sub('[0-9]*', 'Under.and.18',df$Age), gsub('[0-9]*', 'Over.18',df$Age))
  df$Sample = gsub(" ",".",df$Sample)
  df$Sample = gsub("-",".",df$Sample)
  return(df)
}

df<- format_clinical_data(var.ID)

```

## Organize factor levels of variable group dataframe


```{r organizing, warning=FALSE}

organize_vars <- function(df) {
  #Get IDs from synapse table
  synds<-df$synid
  #create factors of clinical variables in synapse table
  group <- factor(df$Clinical.Status)
  sex <- factor(df$Sex)
  age <- factor(df$Age)
  qual <- factor(df$UpdatedTissueQuality)

  #generate clinical variable partitions for heatmap legend
  var.ID <- data.frame(group)

  var.ID$sex <- sex
  var.ID$age <- age
  var.ID$qual <- qual
  return(var.ID)
}

#var.ID <- organize_vars(df)
#var.ID

```


## Filter genes by low expression


```{r filtering, warning=FALSE}

filter_by_low_expressed_genes <- function(master.table) {
  #Filter lowly expressed genes
  sum.table <- master.table %>% 
    group_by(TXID)%>%
    mutate(sum = sum(TPM))#
           #rowSums(.[grep("TPM", names(.))]))
  #keep<-sum.table[!(sum.table$sum<1),]
  #row.names(keep) <- keep$TXID
  #counts <- keep %>% dplyr:: select(contains("Count"))
  #names(counts) <- sapply(strsplit(names(counts), ".C"), '[', 1)
  counts<-subset(sum.table,sum>1)%>%
    dplyr::select(c(TXID,NumReads,synid))%>%
    pivot_wider(values_from = 'NumReads',names_from='synid')%>%
    tibble::column_to_rownames('TXID')
  
  return(counts)
}
counts <- filter_by_low_expressed_genes(master.table)

```

## Do DE analysis on sex variable groups


```{r analysingSex, warning=FALSE}
library(Biobase)
sex_res <- limmaTwoFactorDEAnalysis(counts, rownames(subset(var.ID,Sex=='Male')),
                                    rownames(subset(var.ID,Sex=='Female')))
                                   

plotTopGenesHeatmap(sex_res, counts, identifiers,'sex',var.ID, adjpval=0.1, upload=TRUE, parentID='syn25323411')

genes.with.values<-sex_res%>%
  dplyr::select(Gene='featureID',value='logFC')
                   
plotOldGSEA(genes.with.values,NULL,'sexDifferences',useEns=TRUE)

```

## Do DE analysis on life status variable groups


```{r analysingExist, warning=FALSE}
exist_res <- limmaTwoFactorDEAnalysis(counts, 
                                      row.names(subset(var.ID,Clinical.Status%in%c('Alive','NED','Alive with metastatic disease'))),
                                      row.names(subset(var.ID,Clinical.Status=='Deceased')))

plotTopGenesHeatmap(exist_res, counts, identifiers,'exist',var.ID, adjpval=0.1, upload=TRUE, parentID='syn25323411')


genes.with.values<-exist_res%>%
  dplyr::select(Gene='featureID',value='logFC')
plotOldGSEA(genes.with.values,NULL,'prognosisDiff',useEns=TRUE)
```

## Do DE analysis on age variable groups


```{r analysingAge, warning=FALSE}
age_res <- limmaTwoFactorDEAnalysis(counts,  
                                    row.names(subset(var.ID,Age>18)),
                                    row.names(subset(var.ID,Age<19)))

plotTopGenesHeatmap(age_res, counts, identifiers,'age',var.ID, adjpval=0.1, upload=TRUE, parentID='syn25323411')


genes.with.values<-age_res%>%
  dplyr::select(Gene='featureID',value='logFC')
plotOldGSEA(genes.with.values,NULL,'ageDifferences',useEns=TRUE)
```

## Do DE analysis on sample quality variable groups


```{r analysingQual, warning=FALSE}
qual_res <- limmaTwoFactorDEAnalysis(counts, 
                                     row.names(subset(var.ID,MicroTissueQuality%in%c('Good','Robust'))), 
                                     row.names(subset(var.ID,MicroTissueQuality=='Unusable')))

plotTopGenesHeatmap(qual_res, counts, identifiers,'age',var.ID, adjpval=0.1, upload=TRUE, parentID='syn25323411')


genes.with.values<-qual_res%>%
  dplyr::select(Gene='featureID',value='logFC')
plotOldGSEA(genes.with.values,NULL,'qualDifferences',useEns=TRUE)
```
