on:
  push:
    paths:
      - results/*Rmd
      - .github/workfows/*

name: Render RMDs

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
     - uses: actions/checkout@v2
     - uses: r-lib/actions/setup-r@v1
     - uses: r-lib/actions/setup-pandoc@v1
     - uses: r-lib/actions/setup-tinytex@v1
     - name: Install synapse client
       run: pip install synapseclient
     - name: Install rmarkdown
       run: Rscript -e 'install.packages("rmarkdown")'
     - name: Install devtools
       run: Rscript -e 'install.packages("devtools"); install.packages("gridExtra")'
     - name: Install Python dependencies
       run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install python3-virtualenv
          sudo apt-get install python3-venv
       shell: /bin/bash {0}
     - name: Install packages
       run: Rscript -e 'devtools::install_github("rstudio/reticulate");devtools::build();devtools::install()'
     - name: Render my document to all types
       run: Rscript -e 'for(file in list.files("results/",pattern="*Rmd")) rmarkdown::render(paste0("results/",file))'
#     - name: Store on synapse
#       run: for $file in results/*html do synapse store $file --parentId syn26093047
#       with:
