on:
  push:
    paths:
      - results/*Rmd

name: Render RMDs

jobs:
  render:
    runs-on: macOS-latest
    steps:
     - uses: actions/checkout@v2
     - uses: r-lib/actions/setup-r@v1
     - uses: r-lib/actions/setup-pandoc@v1
     - uses: r-lib/actions/setup-tinytex@v1
     - name: Install rmarkdown
       run: Rscript -e 'install.packages("rmarkdown")'
     - name: Install devtools
       run: Rscript -e 'install.packageS("devtools")'
     - name: Install packages
       run: Rscript -e 'devtools::build();devtools::install()'
     - name: Render my document to all types
       run: Rscript -e 'rmarkdown::render("results/02-ReCalcGrowthMetrics.Rmd", output_format = "all")'
